[package]
name = "luminal_tracing"
version = "0.1.0"
edition.workspace = true

[dependencies]
tracing = "0.1.43"
tracing-appender = "0.2.4"
tracing-perfetto-sdk-layer = "0.13.0"
tracing-perfetto-sdk-schema = "0.13.0"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }